version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: refood_db
      POSTGRES_USER: refood
      POSTGRES_PASSWORD: refood
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network

  api:
    build: ./api
    ports:
      - "8080:80"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - ./api/app:/code/app
    depends_on:
      - postgres
    networks:
      - shared-network

volumes:
  postgres-data:

networks:
  shared-network:
